### ISSUE TITLE
Text from corpus.xml

### ISSUE THREAD

**Issue by tombernas** [dracor-org/poldracor#4]
Is it possible to insert text from the corpus.xml file into the poldracor home page? We need this to complete and settle the project.
https://github.com/dracor-org/poldracor/blob/main/corpus.xml

**Comment by lehkost** [comment]
As far as I can see, this is already happening, please see https://staging.dracor.org/pol – directly under the "Polish Drama Corpus" headline, there is the text from the file "corpus.xml" ("Edited by members [etc.]").

The bigger question would be, is the PolDraCor corpus ready to be integrated in our production server (thus losing the "staging." prefix)?

**Comment by cmil** [comment]
> As far as I can see, this is already happening, please see https://staging.dracor.org/pol – directly under the "Polish Drama Corpus" headline, there is the text from the file "corpus.xml" ("Edited by members [etc.]").

I reloaded the corpus, that's why the text now appears on staging. Usually this should be updated automatically whenever corpus.xml is edited. But it may be that the webhook was not working correctly the last time that happened because of the API changes we made for the v1 release.

From now on changes to your corpus.xml (and other TEI files for that matter) should be propagated to staging.dracor.org within a couple of minutes after pushing them to GitHub. If that's not the case, please open a new issue.

**Comment by tombernas** [comment]
Thank you for reloading the corpus! :) And yes, we are ready to move to the main server!
